import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const auditFields = { createdAt: v.number(), updatedAt: v.number(), createdBy: v.optional(v.id("users")), updatedBy: v.optional(v.id("users")) };

export default defineSchema({
  users: defineTable({ normalizedEmail: v.string(), accountKind: v.union(v.literal("professional"), v.literal("customer"), v.literal("platform_admin")), status: v.union(v.literal("pending_verification"), v.literal("active"), v.literal("locked"), v.literal("suspended")), emailVerifiedAt: v.optional(v.number()), failedLoginCount: v.number(), lockedUntil: v.optional(v.number()), deletedAt: v.optional(v.number()), deletedBy: v.optional(v.id("users")), ...auditFields }).index("by_normalized_email", ["normalizedEmail"]).index("by_status", ["status"]),
  userProfiles: defineTable({ userId: v.id("users"), firstName: v.optional(v.string()), lastName: v.optional(v.string()), locale: v.string(), ...auditFields }).index("by_user", ["userId"]),
  credentials: defineTable({ userId: v.id("users"), kind: v.literal("password"), passwordHash: v.string(), hashVersion: v.number(), rotatedAt: v.number(), ...auditFields }).index("by_user", ["userId"]),
  sessions: defineTable({ userId: v.id("users"), tokenHash: v.string(), expiresAt: v.number(), lastSeenAt: v.number(), revokedAt: v.optional(v.number()), revokeReason: v.optional(v.string()), ipHash: v.optional(v.string()), userAgent: v.optional(v.string()), ...auditFields }).index("by_token_hash", ["tokenHash"]).index("by_user", ["userId", "revokedAt"]),
  emailVerificationTokens: defineTable({ userId: v.id("users"), tokenHash: v.string(), expiresAt: v.number(), usedAt: v.optional(v.number()), invalidatedAt: v.optional(v.number()), createdAt: v.number() }).index("by_hash", ["tokenHash"]).index("by_user", ["userId"]),
  passwordResetTokens: defineTable({ userId: v.id("users"), tokenHash: v.string(), expiresAt: v.number(), usedAt: v.optional(v.number()), invalidatedAt: v.optional(v.number()), requestedIpHash: v.optional(v.string()), createdAt: v.number() }).index("by_hash", ["tokenHash"]).index("by_user", ["userId"]),
  organizations: defineTable({ name: v.string(), slug: v.string(), status: v.union(v.literal("active"), v.literal("suspended"), v.literal("closed")), deletedAt: v.optional(v.number()), deletedBy: v.optional(v.id("users")), ...auditFields }).index("by_slug", ["slug"]).index("by_status", ["status"]),
  memberships: defineTable({ organizationId: v.id("organizations"), userId: v.id("users"), role: v.union(v.literal("owner"), v.literal("admin"), v.literal("manager"), v.literal("editor"), v.literal("analyst"), v.literal("viewer")), status: v.union(v.literal("invited"), v.literal("active"), v.literal("suspended"), v.literal("removed")), ...auditFields }).index("by_org_user", ["organizationId", "userId"]).index("by_user_status", ["userId", "status"]).index("by_org_status", ["organizationId", "status"]),
  invitations: defineTable({ organizationId: v.id("organizations"), emailHash: v.string(), role: v.string(), tokenHash: v.string(), expiresAt: v.number(), acceptedAt: v.optional(v.number()), revokedAt: v.optional(v.number()), ...auditFields }).index("by_token", ["tokenHash"]).index("by_org", ["organizationId", "createdAt"]),
  securityEvents: defineTable({ userId: v.optional(v.id("users")), type: v.string(), result: v.string(), ipHash: v.optional(v.string()), metadata: v.optional(v.any()), createdAt: v.number() }).index("by_user_time", ["userId", "createdAt"]).index("by_type_time", ["type", "createdAt"]),
  auditEvents: defineTable({ organizationId: v.optional(v.id("organizations")), actorUserId: v.optional(v.id("users")), action: v.string(), targetType: v.string(), targetId: v.optional(v.string()), result: v.union(v.literal("success"), v.literal("denied"), v.literal("failure")), reason: v.optional(v.string()), requestId: v.string(), metadata: v.optional(v.any()), createdAt: v.number() }).index("by_org_time", ["organizationId", "createdAt"]).index("by_actor_time", ["actorUserId", "createdAt"]).index("by_request", ["requestId"]),
  rateLimitBuckets: defineTable({ action: v.string(), keyHash: v.string(), count: v.number(), windowStartedAt: v.number(), blockedUntil: v.optional(v.number()), updatedAt: v.number() }).index("by_action_key", ["action", "keyHash"]),
});
